# Generated by Django 2.1.2 on 2018-10-30 19:40

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fast',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='fast',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=None, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fast',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
