# Generated by Django 2.1.2 on 2018-10-30 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fast', '0002_auto_20181030_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='fast',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 20, 23, 56, 903301, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 20, 24, 13, 493597, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
